Coding multiple neurons and stacking them up together using Numpy


Note: 
That we are avoiding the involvement of  activation function for the sake of simplicity

In [4]:
#Importing packages
import numpy as np

In [ ]:
#Coding a single neuron using numpy
inputs=[1.0,2.0,3.0,2.5]
weights=[0.2,0.8,-0.5,1.0]

bias=

outputs=np.dot(weights, inputs)+bias
print(outputs)

4.8


In [6]:
#Coding layers of neurons using numpy
inputs=[1.0,2.0,3.0,2.5]

weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2.0,3.0,0.5]

layer_outputs=np.dot(weights, inputs)+biases
print(layer_outputs) 

[4.8   1.21  2.385]


In [7]:
weights=np.array(weights)

In [8]:
print(np.dot(inputs,weights.T)+biases)

[4.8   1.21  2.385]


In [18]:
#Layers of Neurons and Batch of Data using Numpy

inputs= np.array([
    [1,2,3,2.5],
    [2,5,-1,2.0],
    [-1.5,2.7,3.3,0.8]
])


weights=np.array([[0.2,0.8,-0.5,1],
   [0.5,-0.91,0.26,-0.5],
   [-0.26,-0.27,0.17,0.87]
   ])
biases=[2.0,3.0,0.5]

outputs=np.dot(inputs,weights.T)+biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 3.01   0.251  1.418]]
