Coding multiple neurons and stacking them up together using Numpy


Note: 
That we are avoiding the involvement of  activation function for the sake of simplicity

In [4]:
#Importing packages
import numpy as np

In [6]:
#Coding a single neuron using numpy
inputs=[1.0,2.0,3.0,2.5]
weights=[0.2,0.8,-0.5,1.0]

bias=[1,2,3,5]

outputs=np.dot(weights, inputs)+bias
print(outputs)

[3.8 4.8 5.8 7.8]


In [7]:
#Coding layers of neurons using numpy
inputs=[1.0,2.0,3.0,2.5]

weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2.0,3.0,0.5]

layer_outputs=np.dot(weights, inputs)+biases
print(layer_outputs) 

[4.8   1.21  2.385]


In [8]:
weights=np.array(weights)

In [9]:
print(np.dot(inputs,weights.T)+biases)

[4.8   1.21  2.385]


In [12]:
#Layers of Neurons and Batch of Data using Numpy

inputs= np.array([
    [1,2,3,2.5],
    [2,5,-1,2.0],
    [-1.5,2.7,3.3,0.8]
])


weights=np.array([[0.2,0.8,-0.5,1],
   [0.5,-0.91,0.26,-0.5],
   [-0.26,-0.27,0.17,0.87]
   ])
biases=np.array([2.0,3.0,0.5])

outputs=np.dot(inputs,weights.T)+biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 3.01   0.251  1.418]]


Adding more layers


In [17]:
inputs=[[1,2,3,2.5],
        [2.,5.,-1.,2],
        [-1.5,2.7,3.3,-0.8]]
weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

biases=[2,3,0.5]

weights2=[[0.1,-0.14,0.5],
          [-0.5,0.12,-0.33],
          [-0.44,0.73,0.13]]

biases2=[-1,2,-0.5]

#Convert lists to numpy arrays
inputs_array=np.array(inputs)
weights_array=np.array(weights)
biases_array=np.array(biases)
weights2_array=np.array(weights2)
biases2_array=np.array(biases2)

#Calculate the output of the first layer

layer1_output=np.dot(inputs_array,weights_array.T)+biases_array
#print(layer1_output)

#Calculate the output of the second layer
layer2_output=np.dot(layer1_output,weights2_array.T)+biases2_array
print(layer2_output)

[[ 0.5031  -1.04185 -1.41865]
 [ 0.2434  -2.7332  -5.7113 ]
 [-0.99314  1.41254 -0.34979]]
