In [2]:
import numpy as np

Case1: When class Targets are different number such as 0,1,2, Here:

        0-Red, 1-Green, 2-Blue

In [3]:
softmax_outputs=np.array([[0.7,0.1,0.2],
                          [0.1,0.5,0.4],
                          [0.02,0.9,0.08]])
class_targets=[0,1,1]
#Indexing
print(softmax_outputs[[0,1,2], class_targets])

[0.7 0.5 0.9]


In [4]:
print(-np.log(softmax_outputs[
    range(len(softmax_outputs)), class_targets
    ]))
neg_log=-np.log(softmax_outputs[range(len(softmax_outputs)),class_targets])
average_loss=np.mean(neg_log)
print(average_loss)

[0.35667494 0.69314718 0.10536052]
0.38506088005216804


In [5]:
# Trying Indexing through loop
# a=[]
# for i in range(len(softmax_outputs)):
#     a.append(softmax_outputs[[i],class_targets[i]])
# a=np.array(a)
# print(a)



Case2: Targets are ONE-HOT Encoded, Here:

        Red-[1 0 0],Green-[0 1 0], Blue-[ 0 0 1]

if Data is one hot encoded, how to extract the relevant predictions

In [35]:
y_true_check=np.array([
    [0,1,0],
    [1,0,0],
    [0,0,1]
])

y_pred_clipped_check=np.array([
    [0.2,0.7,0.1],
    [0.8,0.1,0.1],
    [0.1,0.2,0.7]
])

A=y_true_check*y_pred_clipped_check
B=np.sum(A, axis=1)
print(B)

[0.7 0.8 0.7]


In [36]:
C= -np.log(B)
print(C)

[0.35667494 0.22314355 0.35667494]


Note: We need to prevent very large or very small values when we take log. Hence, we need to clip our predcitions

In [ ]:
# Implemnting the categorical cross entropy class

class Loss_CategoricalCrossentropy(Loss):
    #forward pass
    def forward(self,y_pred,y_true):
        samples=len(y_pred)
        #Clip data to prevent divisions by 0
        #Clip both sides to not drag mean towards any value
        y_pred_clipped=np.clip(y_pred, 1e-7,1-1e-7):