# Backpropagation for a Layer of Multiple Neurons (From Scratch)

This notebook presents a step-by-step implementation of the backpropagation algorithm for a layer containing multiple neurons. 

The implementation is built entirely from scratch using NumPy, with the objective of understanding how gradients flow through a neural network and how weights and biases are updated during training.

In [4]:
import numpy as np

In [8]:
#initial inputs

inputs=np.array([1,2,3,4])

#Initial weights and biases

weights=np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])

biases=np.array([0.1, 0.2, 0.3])

#Learning rate
learning_rate=0.001

# ReLU activation function and its derivative

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x>0,1,0)

#Training Loop

for iteration in range(201):
    #forward pass
    z=np.dot(weights, inputs) +biases
    a=relu(z)
    y=np.sum(a)

    #Calculate loss

    #target_output=0, loss=(y-0)**2=y**2
    loss=y**2 

    #Backward pass
    #gradient of loss with to output
    dL_dy=2*y

    #gradient of y with respect to a
    dy_da=np.ones_like(a)

    # gradient of loss w.r.t a
    dL_da=dL_dy*dy_da

    #gradient of a w.r.t z(Relu derivative)
    da_dz=relu_derivative(z)

    # gradient of loss with respect to z
    dl_dz=dL_da* da_dz

    # gradients of z with respect to weights and biases

    dL_dW=np.outer(dl_dz, inputs)
    dl_db=dl_dz

    #update weights and biases

    weights-=learning_rate*dL_dW
    biases-=learning_rate*dl_db
    
    #Print the loss every 20 iterations
    if iteration%20==0:
        print(f"Iteration:{iteration}, Loss:{loss}")

#Final weights and biases
print("Final weights:\n", weights)
print("Final biases :\n", biases)


Iteration:0, Loss:466.56000000000006
Iteration:20, Loss:5.32959636083938
Iteration:40, Loss:0.4119152340489983
Iteration:60, Loss:0.03183621207946751
Iteration:80, Loss:0.0024605654653895997
Iteration:100, Loss:0.00019017282566014768
Iteration:120, Loss:1.4698126966450583e-05
Iteration:140, Loss:1.1359926717817246e-06
Iteration:160, Loss:8.77988980016028e-08
Iteration:180, Loss:6.785824135779993e-09
Iteration:200, Loss:5.244645462652863e-10
Final weights:
 [[-0.00698895 -0.01397789 -0.02096684 -0.02795579]
 [ 0.25975286  0.11950572 -0.02074143 -0.16098857]
 [ 0.53548456  0.27096913  0.00645369 -0.25806174]]
Final biases :
 [-0.00698895 -0.04024714 -0.06451544]
