In [18]:
#Gradients of loss with respect to weights
import numpy as np

dvalues=np.array([[1.,1.,1.],
                  [2., 2., 2.],
                  [3., 3., 3.]])
#We have 3 sets of inputs-samples
inputs=np.array([[1,2,3,2.5],
                 [2., 5., -1., 2],
                 [-1.5, 2.7,3.3, -0.8]])
#sum weights of given input and multiply by the passed-in gradient for this neuron
dweights=np.dot(inputs.T,dvalues)
print(dweights)

[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


In [19]:
#Gradients of the loss with respect to biases

dbiases=np.sum(dvalues, axis=0, keepdims=True)
print(dbiases)

[[6. 6. 6.]]


In [20]:
# Gradients of the loss with respect to inputs

dvalues=np.array([[1.,1.,1.],
                  [2., 2., 2.],
                  [3., 3., 3.]])

weights=np.array([[0.2,0.8,-0.5,1],
                  [0.5,-0.91,0.26, -0.5],
                  [-0.26, -0.27, 0.17, 0.87]]).T
dinputs=np.dot(dvalues, weights.T)

print(dinputs)


[[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]


Code till now


In [30]:
#import packages
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()
import matplotlib.pyplot as plt

In [ ]:

#Dense layer

class Layer_dense:
    #Layer intialization
    def __init__(self, n_inputs, n_neurons):
        self.weights=0.01*np.random.randn(n_inputs, n_neurons)
        self.biases=np.zeros((1,n_neurons))

    #Forward pass
    def forward(self, inputs):
        #Calculate output values from inputs, weights, biases
        self.output=np.dot(inputs, self.weights)+self.biases

In [ ]:
# Relu activation 
class Activation_Relu:
    #forward pass
    def forward(self,inputs):
        #Calculate output values from input
        self.inputs=input
        self.output=np.maximum(0,inputs)

        #Backward pass

        def backward(self, dvalues):
            #since we need to modify the original variable 
            #Make a copy of the values first

            self.dinputs=dvalues.copy()
            self.dinputs[self.inputs<=0]=0


In [24]:
#Softmax activation

class Activation_Softmax:
    # Forward Pass
    def forward(self, inputs):
        #Get unnormalized probabilities
        exp_values=np.exp(inputs-np.max(inputs, axis=1, keepdims=True))
        #Normalize them for each sample
        probabilities=exp_values/np.sum(exp_values, axis=1, keepdims=True)
        self.output=probabilities

In [25]:
# Implementing the loss class

class Loss:
    # Calculates the data and regularization losses
    def calculate(self, output,y):
        #Calculate sample losses
        sample_losses=self.forward(output,y)
        #Calculate mean loss
        data_loss=np.mean(sample_losses)
        #return Loss
        return data_loss

#we implement the class loss just for the sake of simplicity
#So we can also see weight values

In [26]:
# Implemnting the categorical cross entropy class

class Loss_CategoricalCrossentropy(Loss):
    #forward pass
    def forward(self,y_pred,y_true):
        samples=len(y_pred)
        #Clip data to prevent divisions by 0
        #Clip both sides to not drag mean towards any value
        y_pred_clipped=np.clip(y_pred, 1e-7,1-1e-7)
        if len(y_true.shape)==1:
            correct_confidences=y_pred_clipped[
                range(samples),
                y_true
            ]
            #Mask values -only for one-hot encoded labels
        elif len(y_true.shape)==2:
            correct_confidences = np.sum(
                y_pred_clipped*y_true,
                axis=1
            )
        #losses
        negative_log_likelihoods=-np.log(correct_confidences)
        return negative_log_likelihoods


# Adding the "Backward" Method in the Layer-Dense class

In [28]:
class Layer_dense:
    #backward pass
    def backward(self, dvalues):
        #gradients on parameters
        self.dweights=np.dot(self.inputs.T, dvalues)
        self.dbiases=np.sum(dvalues, axis=0,keepdims=True)

        #gradient on values
        self.dinputs=np.dot(dvalues, self.weights.T)